<?php

namespace Veta\HomeworkBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Doctrine\ORM\QueryBuilder;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    /**
     * @return QueryBuilder
     */
    public function findMostRecentQueryBuilder()
    {
        $qb = $this->createQueryBuilder('u')
            ->orderBy('u.dateCreate', 'DESC')

        ;

        return $qb;
    }

    /**
     * @return Query
     */
    public function findMostRecentQuery()
    {
        return $this->findMostRecentQueryBuilder()->getQuery();
    }

    /**
     * @return array
     */
    public function findMostRecent()
    {
        return $this->findMostRecentQuery()->getResult();
    }
}
