<?php

namespace Veta\HomeworkBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Doctrine\ORM\QueryBuilder;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /**
     * @param int $limit
     * @return QueryBuilder
     */
    public function findMostRecentQueryBuilder($limit = 100)
    {
        $qb = $this->createQueryBuilder('u')
            ->orderBy('u.dateCreate', 'DESC')
            ->setMaxResults($limit)

        ;

        return $qb;
    }

    /**
     * @param int $limit
     * @return Query
     */
    public function findMostRecentQuery($limit = 100)
    {
        return $this->findMostRecentQueryBuilder($limit)->getQuery();
    }

    /**
     * @param int $limit
     * @return array
     */
    public function findMostRecent($limit = 100)
    {
        return $this->findMostRecentQuery($limit)->getResult();
    }

    /**
     * @param int $limit
     * @return QueryBuilder
     */
    public function findMostOldQueryBuilder($limit = 100)
    {
        $qb = $this->createQueryBuilder('u')
            ->orderBy('u.dateCreate', 'ASC')
            ->setMaxResults($limit)

        ;

        return $qb;
    }

    /**
     * @param int $limit
     * @return Query
     */
    public function findMostOldQuery($limit = 100)
    {
        return $this->findMostOldQueryBuilder($limit)->getQuery();
    }

    /**
     * @param int $limit
     * @return array
     */
    public function findMostOldRecent($limit = 100)
    {
        return $this->findMostOldQuery($limit)->getResult();
    }

    /**
     * @param int $limit
     * @return QueryBuilder
     */
    public function findOrderByTitleUpBuilder($limit = 100)
    {
        $qb = $this->createQueryBuilder('u')
            ->orderBy('u.title', 'DESC')
            ->setMaxResults($limit)

        ;

        return $qb;
    }

    /**
     * @param int $limit
     * @return Query
     */
    public function findOrderByTitleUpQuery($limit = 100)
    {
        return $this->findOrderByTitleUpBuilder($limit)->getQuery();
    }

    /**
     * @param int $limit
     * @return array
     */
    public function findOrderByTitleUp($limit = 100)
    {
        return $this->findOrderByTitleUpQuery($limit)->getResult();
    }

    /**
     * @param int $limit
     * @return QueryBuilder
     */
    public function findOrderByTitleDownBuilder($limit = 100)
    {
        $qb = $this->createQueryBuilder('u')
            ->orderBy('u.title', 'ASC')
            ->setMaxResults($limit)

        ;

        return $qb;
    }

    /**
     * @param int $limit
     * @return Query
     */
    public function findOrderByTitleDownQuery($limit = 100)
    {
        return $this->findOrderByTitleDownBuilder($limit)->getQuery();
    }

    /**
     * @param int $limit
     * @return array
     */
    public function findOrderByTitleDown($limit = 100)
    {
        return $this->findOrderByTitleDownQuery($limit)->getResult();
    }
}
