<?php

namespace Veta\HomeworkBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Doctrine\ORM\QueryBuilder;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /**
     * @param int $limit
     * @return QueryBuilder
     */
    public function findMostRecentQueryBuilder($limit = 100)
    {
        $qb = $this->createQueryBuilder('u')
            ->orderBy('u.dateCreate', 'DESC')
            ->setMaxResults($limit)

        ;

        return $qb;
    }

    /**
     * @param int $limit
     * @return Query
     */
    public function findMostRecentQuery($limit = 100)
    {
        return $this->findMostRecentQueryBuilder($limit)->getQuery();
    }

    /**
     * @param int $limit
     * @return array
     */
    public function findMostRecent($limit = 100)
    {
        return $this->findMostRecentQuery($limit)->getResult();
    }
}
