<?php

namespace Veta\HomeworkBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Doctrine\ORM\QueryBuilder;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    /**
     * @param int $limit
     * @return QueryBuilder
     */
    public function findLimitedQueryBuilder($limit = 100)
    {
        $qb = $this->createQueryBuilder('u')
            ->setMaxResults($limit)

        ;

        return $qb;
    }

    /**
     * @param int $limit
     * @return Query
     */
    public function findLimitedQuery($limit = 100)
    {
        return $this->findLimitedQueryBuilder($limit)->getQuery();
    }

    /**
     * @param int $limit
     * @return array
     */
    public function findLimited($limit = 100)
    {
        return $this->findLimitedQuery($limit)->getResult();
    }
}
