veta_homework_setup:
    path:      /
    defaults: { _controller: VetaHomeworkBundle:Site:setup }
    options:
        expose: false

veta_homework_homepage:
    path:      /{_locale}/
    defaults: { _controller: VetaHomeworkBundle:Site:index }
    requirements:
        _locale: en|uk
    options:
        expose: true

veta_homework_post_index:
    path:     /{_locale}/post
    defaults: { _controller: VetaHomeworkBundle:Post:index }
    methods: [GET]
    requirements:
        _locale: en|uk
    options:
        expose: true

veta_homework_post_search:
    path:     /{_locale}/post/search
    defaults: { _controller: VetaHomeworkBundle:Post:search }
    methods: [GET]
    requirements:
        _locale: en|uk
    options:
        expose: false

veta_homework_post_likes:
    path:     /post/like
    defaults: { _controller: VetaHomeworkBundle:Post:likes }
    methods: [POST]
    options:
        expose: false

veta_homework_post_view:
    path:     /{_locale}/post/{slug}
    defaults: { _controller: VetaHomeworkBundle:Post:view }
    methods: [GET]
    requirements:
        slug: '[\w\-]+'
        _locale: en|uk
    options:
        expose: true

veta_homework_comment_create:
    path:     /comment
    defaults: { _controller: VetaHomeworkBundle:Comment:create }
    methods: [POST]
    options:
        expose: false

veta_homework_category_index:
    path:    /{_locale}/category/{slug}
    defaults: { _controller: VetaHomeworkBundle:Category:index }
    methods: [GET]
    requirements:
        slug: '[\w\-]+'
        _locale: en|uk
    options:
        expose: true

veta_homework_tag_index:
    path:     /{_locale}/tag/{slug}
    defaults: { _controller: VetaHomeworkBundle:Tag:index }
    methods: [GET]
    requirements:
        slug: '[\w\-]+'
        _locale: en|uk
    options:
        expose: true
