veta_homework_homepage:
    path:     /
    defaults: { _controller: VetaHomeworkBundle:Default:index }

veta_homework_admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

veta_homework_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
