veta_homework_homepage:
    path:     /
    defaults: { _controller: VetaHomeworkBundle:Site:index }

veta_homework_admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

veta_homework_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

veta_homework_redcode_tree:
    resource: "@RedCodeTreeBundle/Resources/config/routing.yml"
    prefix:   /admin

veta_homework_post_index:
    path:     /post
    defaults: { _controller: VetaHomeworkBundle:Post:index }

veta_homework_comment_index:
    path:     /comment
    defaults: { _controller: VetaHomeworkBundle:Comment:index }

veta_homework_category_index:
    path:     /category/{slug}
    defaults: { _controller: VetaHomeworkBundle:Category:index }
    methods: [GET]
    requirements:
        slug: '[\w\-]+'
