veta_homework_homepage:
    path:     /
    defaults: { _controller: VetaHomeworkBundle:Site:index }

veta_homework_post_index:
    path:     /post
    defaults: { _controller: VetaHomeworkBundle:Post:index }
    methods: [GET]

veta_homework_post_search:
    path:     /post/search
    defaults: { _controller: VetaHomeworkBundle:Post:search }
    methods: [GET]

veta_homework_post_view:
    path:     /post/{slug}
    defaults: { _controller: VetaHomeworkBundle:Post:view }
    methods: [GET]
    requirements:
        slug: '[\w\-]+'

veta_homework_comment_create:
    path:     /comment
    defaults: { _controller: VetaHomeworkBundle:Comment:create }
    methods: [POST]

veta_homework_category_index:
    path:     /category/{slug}
    defaults: { _controller: VetaHomeworkBundle:Category:index }
    methods: [GET]
    requirements:
        slug: '[\w\-]+'

veta_homework_tag_index:
    path:     /tag/{slug}
    defaults: { _controller: VetaHomeworkBundle:Tag:index }
    methods: [GET]
    requirements:
        slug: '[\w\-]+'
