services:

    veta_homework.admin.post_admin:
        class: Veta\HomeworkBundle\Admin\PostAdmin
        arguments: [~,Veta\HomeworkBundle\Entity\Post, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Posts", icon: "<i class=\"fa fa-th\" aria-hidden=\"true\"></i>" }
        calls:
            - [ setTranslationDomain, [ 'VetaHomeworkBundle' ] ]

    veta_homework.admin.category_admin:
        class: Veta\HomeworkBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Classification", label: "Categories", icon: "<i class=\"fa fa-tags\" aria-hidden=\"true\"></i>" }
        arguments:
            - ~
            - 'Veta\HomeworkBundle\Entity\Category'
            - 'VetaHomeworkBundle:CategoryAdmin'
            - 'title'
        calls:
            - [ setTranslationDomain, [ 'VetaHomeworkBundle' ] ]

    veta_homework.admin.tag_admin:
        class: Veta\HomeworkBundle\Admin\TagAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Classification", label: "Tags", icon: "<i class=\"fa fa-tags\" aria-hidden=\"true\"></i>" }
        arguments:
            - ~
            - Veta\HomeworkBundle\Entity\Tag
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [ 'VetaHomeworkBundle ' ] ]

    veta_homework.admin.user_admin:
        class: Veta\HomeworkBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Administration", label: "Users", icon: "<i class=\"fa fa-cogs\" aria-hidden=\"true\"></i>" }
        arguments:
            - ~
            - Veta\HomeworkBundle\Entity\User
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [ 'VetaHomeworkBundle' ] ]

    veta_homework.admin.comment_admin:
        class: Veta\HomeworkBundle\Admin\CommentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Comments", icon: "<i class=\"fa fa-th\" aria-hidden=\"true\"></i>" }
        arguments:
            - ~
            - Veta\HomeworkBundle\Entity\Comment
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [ 'VetaHomeworkBundle' ] ]

    veta_homework.menu.menu_builder:
        class: Veta\HomeworkBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@doctrine.orm.entity_manager"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
            - { name: knp_menu.menu_builder, method: createSidebarMenu, alias: sidebar }

    veta_homework.event_listener.locale_listener:
        class: Veta\HomeworkBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }

    veta_homework.event_listener.exception_listener:
        class: Veta\HomeworkBundle\EventListener\ExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    veta_homework.event_listener.request_listener:
        class: Veta\HomeworkBundle\EventListener\RequestListener
        arguments: ["@twig", "@form.factory", "@router"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    veta_homework.sitemap.post_subscriber:
        class:     Veta\HomeworkBundle\EventListener\SitemapSubscriber
        arguments:
            - "@router"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: "kernel.event_subscriber", priority: 100 }
