services:

    veta_homework.admin.post_admin:
          class: Veta\HomeworkBundle\Admin\PostAdmin
          arguments: [~,Veta\HomeworkBundle\Entity\Post, ~]
          tags:
              - { name: sonata.admin, manager_type: orm, group: "Content", label: "Post", icon: "<i class=\"fa fa-th\" aria-hidden=\"true\"></i>" }

    veta_homework.admin.category_admin:
        class: Veta\HomeworkBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Classification", label: "Category", icon: "<i class=\"fa fa-tags\" aria-hidden=\"true\"></i>" }
        arguments:
            - ~
            - Veta\HomeworkBundle\Entity\Category
            - VetaHomeworkBundle:CategoryAdmin
            - 'title'
        calls:
            - [ setTranslationDomain, [Veta\Homeworkb\Bundle]]

    veta_homework.admin.tag_admin:
        class: Veta\HomeworkBundle\Admin\TagAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Classification", label: "Tag", icon: "<i class=\"fa fa-tags\" aria-hidden=\"true\"></i>" }
        arguments:
            - ~
            - Veta\HomeworkBundle\Entity\Tag
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [Veta\Homeworkb\Bundle]]

    veta_homework.admin.comment_admin:
        class: Veta\HomeworkBundle\Admin\CommentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Comment", icon: "<i class=\"fa fa-th\" aria-hidden=\"true\"></i>" }
        arguments:
            - ~
            - Veta\HomeworkBundle\Entity\Comment
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [Veta\Homeworkb\Bundle]]

    veta_homework.menu.menu_builder:
        class: Veta\HomeworkBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
            - { name: knp_menu.menu_builder, method: createSidebarMenu, alias: sidebar }
